.\"
.\" Copyright (c) 2009-2010
.\" Jesco Freund <aihal@users.sourceforge.net>
.\"
.\" Permission to use, copy, modify, and distribute this software for any
.\" purpose with or without fee is hereby granted, provided that the above
.\" copyright notice and this permission notice appear in all copies.
.\"
.\" THE SOFTWARE IS PROVIDED "AS IS" AND THE AUTHOR DISCLAIMS ALL WARRANTIES
.\" WITH REGARD TO THIS SOFTWARE INCLUDING ALL IMPLIED WARRANTIES OF
.\" MERCHANTABILITY AND FITNESS. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR
.\" ANY SPECIAL, DIRECT, INDIRECT, OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES
.\" WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR PROFITS, WHETHER IN AN
.\" ACTION OF CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION, ARISING OUT OF
.\" OR IN CONNECTION WITH THE USE OR PERFORMANCE OF THIS SOFTWARE.
.\"
.\" $Id$
.\"
.\"
.Dd May 1, 2010
.Dt CDEPLOY 1
.Os
.Sh NAME
.Nm cdeploy
.Nd deploy a set of configuration files to a target file system
.Sh SYNOPSIS
.Nm
.Op Fl chnvDSX
.Op Fl b Ar backup-dir
.Op Fl d Ar destdir
.Op Fl u Ar user
.Op Fl g Ar group
.Op Fl m Ar mode
.Op Fl x Ar pattern
.Sh DESCRIPTION
The
.Nm
script was written to deploy configuration files (or any other kind
of files) from a local directory tree (\(lqsource tree\(rq) to another 
directory tree (\(lqtarget tree\(rq, by default the root of the file system).
.Pp
.Nm
sticks to the layout of the source tree.
Missing directories in the target tree will be created (if permission
is granted to do so); already existing files will be replaced by the
version from the source tree. Source files replacing existing target files 
will be deployed with owner, group and permission of the original target file.
.Pp
.Nm
creates a backup of the original file before replacing it. These backups are
stored as freshly created source tree. In case of trouble with the deployed
files, the backup can be restored by simply deploying it like any other source
tree.
.Sh OPTIONS
The following options are available:
.Bl -tag -width indent
.It Fl b Ar backup-dir
Specify a location where the backup will be created. By default,
.Nm
uses
.Ar ~/.cdeploy
to store backups.
.It Fl c
Only deploy files if the source file differs from the target file.
Equity of source and target file are tested by comparing their MD5
fingerprint generated by OpenSSL
.Xr dgst 1
.It Fl D
Do not invoke
.Xr cap_mkdb 1
after having deployed a database template file. This is the default behaviour
on all systems except FreeBSD.
.It Fl d Ar destdir
Set
.Ar destdir
as root directory for the deployment target. The complete source directory tree will be
deployed into the given target directory.
.Nm
uses
.Ar /
as default deployment target.
.It Fl g Ar group
Deploy files with group
.Ar group
if automatic detection fails (e. g. if there is not yet a target file to replace)
.It Fl h
Print a help message including a short usage summary and exit.
.It Fl l Ar loglevel
Set log level to
.Ar loglevel .
Valid log levels are
.Ar DEBUG ,
.Ar INFO ,
.Ar WARN 
and
.Ar ERROR .
This option controls the amount of information dumped to 
.Xr stdout 4 .
By default, the log level is set to 
.Ar WARN .
.It Fl m Ar mode
Deploy files with mode
.Ar mode
if automatic detection fails (e. g. if there is not yet a target file to replace)
.It Fl n
This option suppresses any escape sequences in the output generated by
.Nm .
It is particularly useful when working on a terminal which cannot process color
escape sequences, or when the output of
.Nm
gets redirected to a file.
.Pp
\fBPlease note:\fP
This option should be specified as early as possible since before it has been processed,
any output will still contain escape sequences.
.It Fl S
This flag causes
.Nm
to run in simulation mode. In simulation mode, no modifications to the target
directory structure will be made. However,
.Nm
will test whether all necessary modifications \fIcould\fP be made.
.It Fl u Ar user
Deploy files with owner
.Ar user
if automatic detection fails (e. g. if there is not yet a target file to replace)
.It Fl v
Print version information and exit.
.It Fl X
Ignore the exclusion pattern. By default,
.Nm
excludes files and directories originating from common version control systems like
CVS, Subversion, Mercurial and Git. This option turns off exclusion completely.
.It Fl x Ar pattern
Exclude all files matching
.Ar pattern
from being deployed.
.Ar pattern
may be a regular expression; extended regular expressions are also supported, as long
as they are understood by
.Xr grep 1 .
The default exclusion pattern is
.Ar "\.svn|\.hg|\.cvs|\.git"
.Sh EXIT STATUS
The
.Nm
utility exits 0 on success, and >0 if an error occurs.
.Sh EXAMPLES
To deploy the content of 
.Li "~/config" ,
one would use:
.Pp
.Dl "cd ~/config"
.Dl "cdeploy"
.Pp
To test which files would be replaced, one would use:
.Pp
.Dl "cdeploy -c -S"
.Pp
To skip the creation of backups (which is actually a bad idea),
one would set the backup directory to /dev/null:
.Pp
.Dl "cdeploy -b /dev/null"
.Pp
.Sh COMPATIBILITY
Compatibility has been tested with the FreeBSD
.Xr sh 1
command interpreter (FreeBSD 7 and 8) and the GNU
.Xr bash 1
(Bourne-Again SHell), version 4.1.5
.Sh SEE ALSO
.Xr cap_mkdb 1 ,
.Xr grep 1 ,
.Xr install 1 ,
.Sh BUGS
Hopefully none. In case you encounter one, please contact the author.
.Sh AUTHOR
Jesco Freund <aihal@users.sourceforge.net>
